# Generated by Django 4.2.5 on 2024-01-06 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='embed_code',
            field=models.TextField(default=''),
        ),
    ]
