# Generated by Django 4.2.5 on 2024-01-06 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veapp', '0003_remove_video_youtube_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='channel_name',
            field=models.CharField(default='Zee Music Company', max_length=255),
        ),
    ]
