# Generated by Django 4.2.5 on 2024-01-07 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veapp', '0010_video_descriptionheading'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='descriptionHeading',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='tags',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
