# Generated by Django 4.2.5 on 2024-01-07 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veapp', '0013_video_download'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='download',
        ),
        migrations.AddField(
            model_name='video',
            name='downloads',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userinteraction',
            name='likes',
            field=models.CharField(blank=True, choices=[('LIKE', 'Like'), ('DISLIKE', 'Dislike')], default=None, max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='comments',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='video',
            name='disLikes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='video',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='video',
            name='shares',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='video',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
