# Generated by Django 4.2.5 on 2024-01-07 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veapp', '0015_remove_video_dislikes_remove_video_downloads_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='likes',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
