# Generated by Django 4.2.5 on 2024-01-07 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veapp', '0016_alter_video_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinteraction',
            name='likes',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
