# Generated by Django 4.2.5 on 2024-01-07 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veapp', '0017_alter_userinteraction_likes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='dislikes',
            new_name='disLikes',
        ),
        migrations.AlterField(
            model_name='userinteraction',
            name='likes',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='video',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
