# Generated by Django 4.2.5 on 2024-01-07 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veapp', '0018_rename_dislikes_video_dislikes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinteraction',
            name='likes',
            field=models.CharField(blank=True, choices=[('LIKE', 'Like'), ('DISLIKE', 'Dislike')], default=None, max_length=7, null=True),
        ),
    ]
